### ISSUE TITLE
Add system bundle for package com.sun.net.httpserver

### ISSUE THREAD

**Issue by sarod** [diffplug/extensionBundles#2]
Add system bundle for package com.sun.net.httpserver

https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/com/sun/net/httpserver/package-summary.html

**Comment by sarod** [comment]
Hi @nedtwigg,

Do you have an ETA for this publication?

No pressure here I'd just like to now if I can wait for you to publish or if I need to add a system bundle locally in my project for now?

Anyway thanks for this project that soften one of the rough edges when building with Tycho.

**Comment by nedtwigg** [comment]
I just published to bintray, and it's in their queue to be included in jcenter. Once that gets approved (normally 24 hrs, but it is NYE...) then it'll go to mavencentral next. Here's where it's living in the meantime: https://bintray.com/diffplug/opensource/extension.com.sun.net.httpserver

**Comment by nedtwigg** [comment]
Released on jcenter and mavencentral. Closed by https://github.com/diffplug/osgiX/commit/473d2ebbe27b2bb3a00cab59b1a7c8c3a74225da

**Comment by sarod** [comment]
Thanks !!
